### ISSUE TITLE
Change cursor when hovered on SplitUp button

### ISSUE THREAD

**Issue by onaralili** [onaralili/SplitUp#13]
When a user hovers on the SplitUp button (the crab) cursor should be changed to a hand cursor (![image](https://user-images.githubusercontent.com/5898068/46681436-84c42400-cbeb-11e8-808d-bd55aff23ea9.png))
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5898068/46681499-a3c2b600-cbeb-11e8-9700-8e8fb44515aa.png">
P.S The crab is a simple svg file embedded into popup.html. Access the class splitUpBt and assign css on hover to triger cursor on hover https://github.com/onaralili/SplitUp/blob/88992a497b9dbff56372afe0895711d6db99ad55/popup.html#L40

This feature has been requested in #12

**Comment by onaralili** [comment]
> I want to work on this issue.
The issue is yours. Thanks

**Comment by vayupranaditya** [comment]
Is it still open? I'd like to work on this one.

**Comment by onaralili** [comment]
> Is it still open? I'd like to work on this one.

Still open, however, It has been already assigned to @mishramonalisha76.

**Comment by onaralili** [comment]
> Ok then just let @mishramonalisha76 work on this 😀

You are welcome to submit PR. I added another issue #14.
