### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by agampreetsingh** [onaralili/SplitUp#19]
There's a minor UI/ UX issue with the back button. Conventionally, the left headed arrows are used for 'Back'. I as a user initially had issues in understanding the UI in this regard. 
![splitupissue](https://user-images.githubusercontent.com/25278610/46795229-3e93cf80-cd67-11e8-9345-087552e6efec.PNG)

**Comment by onaralili** [comment]
The initial idea was that a user goes back to the tab list. I can see some users may have an issue understand it at first glance. Do you have any suggestion how we can improve it?

**Comment by agampreetsingh** [comment]
I just want it to be flipped horizontally. That's it.

**Comment by onaralili** [comment]
> I just want it to be flipped horizontally. That's it.

Make sense. You are welcome to do PR. Thanks.
