### ISSUE TITLE
Blank Window sections on search

### ISSUE THREAD

**Issue by agampreetsingh** [onaralili/SplitUp#23]
I've noticed that when a keyword is searched, the windows which don't contain any tab containing the match appear as blank sections.`
![image](https://user-images.githubusercontent.com/25278610/46804248-bff75c00-cd7f-11e8-94c3-ca6685b9b426.png)
I hope it is not meant to happen..,

**Comment by onaralili** [comment]
Yes. This certainly an issue. The blank ones shouldn't be visible.
