### ISSUE TITLE
delete single tab in bookmark window

### ISSUE THREAD

**Issue by liv-in-sky** [onaralili/SplitUp#24]
I'm not sure maybe I have already mentioned it: to delete one tab in the bookmark window would be great. is this possible ? it is a little bit confusing. I select a lot of different tabs to bookmark and maybe split somewhere in the future (maybe I close the tabs). the next day I open bookmarks and see that one or two tabs aren't important to me. then I select the two tabs and want to use the basket (delete). but what happens ->all tabs from my session will be deleted. to have the possibility to mark something but the function (delete) is not using this mark is ... if I have deleted the tabs already - I lost all tabs!

thank you and have a good time - armin

**Comment by onaralili** [comment]
@liv-in-sky the issue has been solved. You will be able to remove a tab from the Bookmark page in the same fashion you do in the main page. With a red X button next to the tab.

**Comment by liv-in-sky** [comment]
thanx  - it works - perfect solution

**Comment by liv-in-sky** [comment]
hi onaralili,
short comment.
dark mode rocks !  looks really good

**Comment by onaralili** [comment]
> hi onaralili,
> short comment.
> dark mode rocks ! looks really good

Thanks, glad you like it ✨
