### ISSUE TITLE
Categories for Sessions

### ISSUE THREAD

**Issue by onaralili** [onaralili/SplitUp#35]
To allow a user to create categories such as work, personal etc. rearrange/move tabs among the categories on Bookmark page.
Edit:
Got bunch of feature requests again for this one, hence made it a priority for the next release.

**Comment by agampreetsingh** [comment]
@onaralili I am thinking of implementing the same in the bookmarks page only where each window section will have a dropdown button to select a category. Also, on the bookmarks page, there should be an add catagory button which will unhide a small 'Div' below the header which will have a text box and a save button.
Further, each window section will have a label defining the category it is in.

I hope that would work.

**Comment by onaralili** [comment]
> @onaralili I am thinking of implementing the same in the bookmarks page only where each window section will have a dropdown button to select a category. Also, on the bookmarks page, there should be an add catagory button which will unhide a small 'Div' below the header which will have a text box and a save button.
> Further, each window section will have a label defining the category it is in.
> 
> I hope that would work.

Sounds good. I was thinking to put the category of the window as following:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/5898068/49287551-3a9a4900-f49e-11e8-89a5-54931561648d.png">

Since left corner of the buttons looks kinda empty without category name.
