### ISSUE TITLE
Remove selected tabs in Bookmark page

### ISSUE THREAD

**Issue by onaralili** [onaralili/SplitUp#36]
Currently, selection on the Bookmark page only works for splitting up selected tabs. 
When a user selects tabs and clicks trash icon the extension has to remove selected tabs, if not selected then the entire window will be removed (this is the current behavior).

**Comment by agampreetsingh** [comment]
Hi @onaralili. I think I solved issue #24 with the pull request #26 
I guess this is the same issue.
Correct me if I am wrong.

**Comment by onaralili** [comment]
@agampreetsingh hey Agam, currently, we remove by clicking X button next to tabs. However, when a user selects checkbox and clicks trash it needs to remove those selected ones. 
![remove](https://user-images.githubusercontent.com/5898068/49794063-fb3de900-fd36-11e8-9138-9e49c9510542.gif)
