### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [onaralili/SplitUp#41]
Hi...
Just Came across your awesome project, I'm a logo designer who loves to help contribute to great open source projects.
I want to propose a new logo/icon for your project that will fully represent what your project is all about.

Already working on the idea concept, I will share the concept design here so you can give me your feedback. 

I will appreciate your response...

regards!

**Comment by onaralili** [comment]
@chimzycash Thank you.  I appreciate the initiative. However, currently, there is no need for a new logo.

**Comment by chimzycash** [comment]
Okay... I appreciate your response @onaralili  .. I am always available if you need any logo design for any new Open Source Project... Would be glad to help out.
