### ISSUE TITLE
Extension Shortcut

### ISSUE THREAD

**Issue by yougotwill** [onaralili/SplitUp#42]
Very nice addon! Almost perfect just need the ability to assign a keyboard shortcut on Firefox to toggle. 👍

**Comment by yougotwill** [comment]
@onaralili Hi just wondering when will a new version of the extension be released with these changes?

**Comment by onaralili** [comment]
> @onaralili Hi just wondering when will a new version of the extension be released with these changes?

hi, today i will publish it

**Comment by yougotwill** [comment]
Thank you very much and no problem 👍
