### ISSUE TITLE
"select/deselect all" checkbox at top above all checkboxes

### ISSUE THREAD

**Issue by tastyratz** [onaralili/SplitUp#44]
Having to manually click every tab manually is a lot of extra clicks that could be avoided if a select all master checkbox at the top existed. This could be really handy. 
Especially since search results don't expand to show all tabs across all windows right now (bug? will submit another), there are many unnecessary clicks that could be saved.

**Comment by yougotwill** [comment]
@tastyratz Fixed 🚀
